# cloudbuild.yaml
steps:
- name: 'ubuntu'
  args: [ "touch", "foo" ]
- name: 'ubuntu'
  args: [ "ls", "-l" ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ "run", "--volume", "/workspace:/workspace", "--rm", "ubuntu", "ls", "-l", "/workspace" ]