# (generated with --quick)

from typing import Any, Sequence

Point: Any
Polygon: Any
S2Cell: Any
S2Point: Any
S2Polygon: Any
S2Polyline: Any
folium: module
s2: module
webbrowser: module

def cellid_from_point(point, level: int) -> Sequence: ...
def cellid_from_polygon(polygon, level: int) -> Sequence: ...
def cellid_from_polyline(polyline, level: int) -> Sequence: ...
def get_s2cover_for_s2polygon(s2polygon, level: int) -> Sequence: ...
def plot_cells(cells) -> None: ...
def s2point_from_coord_xy(coord: tuple) -> Any: ...
def s2polygon_from_shapely_point(shapely_point) -> Any: ...
def s2polygon_from_shapely_polygon(shapely_polygon) -> Any: ...
def s2polygon_from_shapely_polyline(shapely_polyine) -> Any: ...
