filegroup(
    name = "poiGroup",
    srcs = [
        "bologna_edges.geojson",
        "bologna_graph.gpickle",
        "bologna_nodes.geojson",
        "bologna_poi.pkl",
				"bologna_streets.pkl",

    ],
    visibility = [
        "//visibility:public",
    ],
)